version: '3'

services:
  postgres:
    image: postgres
    container_name: pasnik-postgres
    volumes:
      - pasnik-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=pasnik
      - POSTGRES_USER=pasnik
      - POSTGRES_PASSWORD=pasnik
  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
  api:
    container_name: pasnik-api
    build:
      context: ""
      dockerfile: docker/serve.DockerFile
    environment:
      - APP_NAME=nestjs-api
      - DB_HOST=postgres
      - DB_USERNAME=pasnik
      - DB_PASSWORD=pasnik
      - DB_DATABASE=pasnik
      - DB_PORT=5432
      - DB_MIGRATIONS=true
      - JWT_SECRET=$JWT_SECRET
    volumes:
      - ./:/app
      - /app/dist
      - node-modules:/app/node_modules
    depends_on:
      - postgres
      - redis
    expose:
      - 3334
  bff:
    container_name: pasnik-bff
    build:
      context: ""
      dockerfile: docker/serve.DockerFile
    ports:
      - "3334:3334"
    environment:
      - APP_NAME=nestjs-bff
      - DB_HOST=postgres
      - DB_USERNAME=pasnik
      - DB_PASSWORD=pasnik
      - DB_DATABASE=pasnik
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=$JWT_SECRET
      - SESSION_SECRET=$SESSION_SECRET
      - API_URL=api:3333
      - BASE_URL=localhost:4200
      - ENABLE_INVITATIONS=$ENABLE_INVITATIONS
      - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
      - GOOGLE_SECRET=$GOOGLE_SECRET
      - SLACK_CLIENT_ID=$SLACK_CLIENT_ID
      - SLACK_SECRET=$SLACK_SECRET
    volumes:
      - ./:/app
      - /app/dist
      - node-modules:/app/node_modules
    depends_on:
      - postgres
      - redis
  phppgadmin:
    image: 'bitnami/phppgadmin'
    environment:
      - DATABASE_HOST=postgres
      - POSTGRESQL_PASSWORD=pasnik
    ports:
      - '8080:8080'
      - '8443:8443'
    depends_on:
      - postgres

volumes:
  pasnik-data:
  node-modules:
