# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  deploy:
    docker:
      - image: circleci/node:14.17.4-browsers
    environment:
      FTP_USER: ${FTP_USER}
      FTP_HOST: ${FTP_HOST}
      FTP_PASS: ${FTP_PASS}
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build -- --prod nestjs-api --sourceMap false
      - run: mv ./dist/apps/nestjs-api/main.js ./dist/apps/nestjs-api/app.js
      - run:
          name: Deploying
          command: node ./ftp-deploy.js

workflows:
  version: 2
  sample:
    jobs:
      - node/test:
          version: '15.1'
      - deploy
