# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

defaults: &defaults
  # working_directory: ./circleci
  docker:
    - image: circleci/node:14.17.4-browsers

jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run build -- --prod nestjs-api --sourceMap false
      - persist_to_workspace:
          root: .
          paths:
            - build
  deploy:
    <<: *defaults
    environment:
      FTP_USER: ${FTP_USER}
      FTP_HOST: ${FTP_HOST}
      FTP_PASS: ${FTP_PASS}
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: mv ./dist/apps/nestjs-api/main.js ./dist/apps/nestjs-api/app.js
      - run:
          name: Deploying
          command: node ./ftp-deploy.js

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - prepare
      - build:
          requires:
            - prepare
      - deploy:
          requires:
            - build
